Lte.WebApp/Controllers/Topic/CollegeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lte.Domain.Regular;
using Lte.Evaluations.Dingli;
using Lte.Evaluations.Entities;
using Lte.Evaluations.Service;
using Lte.Evaluations.ViewHelpers;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;
using Lte.Parameters.Service.Public;

namespace Lte.WebApp.Controllers.Topic
{
    public class CollegeController : Controller, ICollegeController
    {
        private readonly ICollegeRepository _repository;
        private readonly ITownRepository _townRepository;
        private readonly IInfrastructureRepository _infrastructureRepository;
        private readonly IIndoorDistributioinRepository _indoorDistributioinRepository;
        private readonly IENodebRepository _eNodebRepository;
        private readonly ICellRepository _cellRepository;
        private readonly IBtsRepository _btsRepository;
        private readonly ICdmaCellRepository _cdmaCellRepository;

        public CollegeController(ICollegeRepository repository, ITownRepository townRepository,
            IInfrastructureRepository infrastructureRepository, IIndoorDistributioinRepository indoorDistributioinRepository,
            IENodebRepository eNodebRepository, ICellRepository cellRepository,
            IBtsRepository btsRepository, ICdmaCellRepository cdmaCellRepository)
        {
            _repository = repository;
            _townRepository = townRepository;
            _infrastructureRepository = infrastructureRepository;
            _indoorDistributioinRepository = indoorDistributioinRepository;
            _eNodebRepository = eNodebRepository;
            _cellRepository = cellRepository;
            _btsRepository = btsRepository;
            _cdmaCellRepository = cdmaCellRepository;
        }

        public IIndoorDistributioinRepository IndoorDistributioinRepository
        {
            get { return _indoorDistributioinRepository; }
        }

        public IENodebRepository ENodebRepository
        {
            get { return _eNodebRepository; }
        }

        public ICellRepository CellRepository
        {
            get { return _cellRepository; }
        }

        public IBtsRepository BtsRepository
        {
            get { return _btsRepository; }
        }

        public ICdmaCellRepository CdmaCellRepository
        {
            get { return _cdmaCellRepository; }
        }

        public IInfrastructureRepository InfrastructureRepository
        {
            get { return _infrastructureRepository; }
        }

        public ActionResult Map()
        {
            return View();
        }

        public ActionResult List()
        {
            IEnumerable<CollegeInfo> infos = _repository.GetAllList();
            IEnumerable<Town> towns = _townRepository.GetAllList();
            CollegeViewModel viewModel = new CollegeViewModel
            {
                Colleges = infos.Select(x => new CollegeDto(x, towns))
            };
            return View(viewModel);
        }

        [Authorize]
        public ActionResult CollegeDetails(int id)
        {
            CollegeInfo info = _repository.Get(id);
            IEnumerable<Town> towns = _townRepository.GetAllList();
            CollegeDto dto = (info == null)
                ? new CollegeDto()
                : new CollegeDto(info, towns);
            CollegeEditViewModel viewModel = new CollegeEditViewModel
            {
                CollegeDto = dto
            };
            viewModel.Initialize(towns, new Town
            {
                CityName = dto.CityName,
                DistrictName = dto.DistrictName,
                TownName = dto.TownName
            });
            return View(viewModel);
        }

        public ActionResult CollegeCells(int id)
        {
            CollegeInfo info = _repository.Get(id);
            if (info == null)
                return View(new InfrastructureInfoViewModel(id));

            ParametersContainer.UpdateCollegeInfos(this, info);

            return View(new InfrastructureInfoViewModel(id, info.Name)
            {
                StartDate = DateTime.Today.AddDays(-7),
                EndDate = DateTime.Today
            });
        }

        [HttpPost]
        public ActionResult CollgeEdit(CollegeEditViewModel viewModel)
        {
            Town town = _townRepository.GetAll().FirstOrDefault(x =>
                x.CityName == viewModel.CollegeDto.CityName
                && x.DistrictName == viewModel.CollegeDto.DistrictName
                && x.TownName == viewModel.CollegeDto.TownName);
            int townId = town == null ? -1 : town.Id;

            CollegeInfo info = viewModel.CollegeDto.Id == -1
                ? new CollegeInfo()
                : _repository.Get(viewModel.CollegeDto.Id);
            if (info == null)
            {
                TempData["error"] = "该校园不存在。无法修改！";
                return RedirectToAction("List");
            }
            int oldTownId = info.TownId;
            string oldName = info.Name;
            viewModel.CollegeDto.CloneProperties(info);
            info.TownId = townId;
            if (viewModel.CollegeDto.Id == -1)
            {
                _repository.Insert(info);
                TempData["success"] = "新增校园" + info.Name + "信息成功！";
            }
            else
            {
                info.TownId = oldTownId;
                info.Name = oldName;
                TempData["success"] = "修改校园" + info.Name + "信息成功！";
                _repository.Update(info);
            }
            return RedirectToAction("List");
        }

        public ActionResult InfrastructureImport()
        {
            HttpPostedFileBase lteFileBase = Request.Files["lte"];
            HttpPostedFileBase cdmaFileBase = Request.Files["cdma"];
            SaveCollegeInfrastructureService service = new SaveCollegeInfrastructureService(InfrastructureRepository);
            string info = "";

            if (lteFileBase != null && lteFileBase.FileName != "")
            {
                CollegeLteExcelModel lteResults = lteFileBase.ImportLteInfos();
                int eNodebCounts = service.SaveENodebs(lteResults.BtsExcels, ENodebRepository);
                int cellCounts = service.SaveCells(lteResults.CellExcels, CellRepository);
                int lteIndoorCounts = service.SaveLteIndoorDistributions(lteResults.IndoorExcels,
                    IndoorDistributioinRepository);
                info += "新增ENodeB" + eNodebCounts + "个；新增LTE小区" + cellCounts + "个；新增LTE室分" + lteIndoorCounts + "个\n";
            }
            if (cdmaFileBase != null && cdmaFileBase.FileName != "")
            {
                CollegeCdmaExcelImporter cdmaResults = cdmaFileBase.ImportCdmaInfos();
                int btsCounts = service.SaveBtss(cdmaResults.BtsExcels, BtsRepository);
                int cdmaCellCounts = service.SaveCdmaCells(cdmaResults.CellExcels, CdmaCellRepository);
                int cdmaIndoorCounts = service.SaveCdmaIndoorDistributions(cdmaResults.IndoorExcels,
                    IndoorDistributioinRepository);
                info += "新增BTS" + btsCounts + "个；新增CDMA小区" + cdmaCellCounts + "个；新增CDMA室分" + cdmaIndoorCounts + "个";
            }
            TempData["info"] = info;
            return RedirectToAction("List");
        }

        public ActionResult CollegeCoverage(int id)
        {
            CollegeInfo info = _repository.Get(id);
            if (info == null)
                return View(new InfrastructureCoverageViewModel(id));

            ParametersContainer.UpdateCollegeInfos(this, info);
            FileRecordsRepository.UpdateCoverageInfos(ParametersContainer.QueryENodebs, 0.03);
            return View(new InfrastructureCoverageViewModel(id, info.Name));
        }
    }
}

Lte.WebApp/Controllers/Topic/EvaluationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Lte.Domain.Geo.Abstract;
using Lte.Domain.Geo.Entities;
using Lte.Domain.Geo.Service;
using Lte.Domain.Regular;
using Lte.Evaluations.Entities;
using Lte.Evaluations.Infrastructure;
using Lte.Evaluations.Infrastructure.Entities;
using Lte.Evaluations.Kml;
using Lte.Evaluations.ViewHelpers;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;
using Lte.Parameters.Service.Lte;
using Lte.Parameters.Service.Public;
using Lte.WebApp.Models;

namespace Lte.WebApp.Controllers.Topic
{
    public class EvaluationController : Controller
    {
        private readonly ITownRepository townRepository;
        private readonly IENodebRepository eNodebRepository;
        private readonly ICellRepository cellRepository;
        private static List<ENodeb> eNodebList = new List<ENodeb>();
        private const int PageSize = 10;

        public EvaluationController(ITownRepository townRepository,
            IENodebRepository eNodebRepository, ICellRepository cellRepositroy)
        {
            this.townRepository = townRepository;
            this.eNodebRepository = eNodebRepository;
            cellRepository = cellRepositroy;
            
        }

        public void ResetENodebList()
        {
            eNodebList = eNodebRepository.GetAllList();
        }

        public ActionResult RegionDef(int page = 1)
        {
            EvaluationViewModel viewModel =
                new EvaluationViewModel
                {
                    ENodebs = eNodebList.Skip((page - 1) * PageSize).Take(PageSize).ToList(),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = eNodebList.Count()
                    },
                    TrafficLoad = EvaluationSettings.TrafficLoad * 100,
                    CellCoverage = (int)EvaluationSettings.DegreeSpan.GetDistanceInMeter(),
                    DistanceInMeter = EvaluationSettings.DistanceInMeter
                };
            viewModel.InitializeTownList(townRepository);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult RegionDef(ENodebQueryViewModel viewModel, 
            EvaluationInfrastructure infrastructure)
        {
            eNodebList = eNodebRepository.GetAllWithNames(townRepository,
                viewModel, viewModel.ENodebName, viewModel.Address);

            EvaluationViewModel model = new EvaluationViewModel
            {
                ENodebs = eNodebList.Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = 1,
                    ItemsPerPage = PageSize,
                    TotalItems = eNodebList.Count()
                },
                TrafficLoad = EvaluationSettings.TrafficLoad * 100,
                CellCoverage = (int)EvaluationSettings.DegreeSpan.GetDistanceInMeter(),
                DistanceInMeter = EvaluationSettings.DistanceInMeter
            };
            model.InitializeTownList(townRepository);
            ViewBag.RegionList = infrastructure.Region;
            return View(model);
        }

        public ActionResult PointsCalculate(EvaluationInfrastructure infrastructure)
        {
            infrastructure.InitializeRegion();
            if (infrastructure.Region == null || infrastructure.Region.Length == 0
                || infrastructure.CellList.Count == 0)
            {
                TempData["warning"] = "仿真区域设置为空！请先设置仿真区域。";
                return RedirectToAction("RegionDef");
            }
            infrastructure.Region.CalculatePerformance(EvaluationSettings.TrafficLoad);
            TempData["success"] = "仿真数据处理成功！可以查看仿真结果。";
            return RedirectToAction("PointsAnalysis");
        }

        public ActionResult PointsAnalysis(StatValueFieldRepository repository)
        {
            return View(new StatFieldViewModel(repository.FieldList[0])
            {
                FieldLength = 4,
                ColorThemeDescription = "春"
            });
        }

        [HttpPost]
        public ActionResult PointsAnalysis(StatFieldViewModel viewModel,
            StatValueFieldRepository repository)
        {
            for (int i = 0; i < repository.FieldList.Count; i++)
            {
                if (i == (int)viewModel.FieldName.GetStatValueIndex()
                    || repository.FieldList[i].IntervalList.Count == 0)
                {
                    repository.FieldList[i].AutoGenerateIntervals(
                        viewModel.FieldLength, viewModel.ColorThemeDescription.GetColorThemeIndex());
                }
            }
            return View(new StatFieldViewModel(repository.FieldList[(int)viewModel.FieldName.GetStatValueIndex()])
            {
                FieldLength = viewModel.FieldLength,
                ColorThemeDescription = viewModel.ColorThemeDescription
            });
        }

        public ActionResult ExportPoints(string fieldName,
            EvaluationInfrastructure infrastructure,
            StatValueFieldRepository repository)
        {
            if (infrastructure.Region == null || infrastructure.Region.Length == 0
                || infrastructure.CellList.Count == 0)
            {
                TempData["warning"] = "仿真区域设置为空！请先设置仿真区域。";
                return RedirectToAction("RegionDef");
            }
            StatValueField field = repository.FieldList[(int)fieldName.GetStatValueIndex()];
            if (field.IntervalList.Count == 0)
            { 
                TempData["warning"] = "显示区间设置为空！请先设置区间。";
                return RedirectToAction("PointsAnalysis");
            }

            TempData["centerX"] = infrastructure.CellList.Average(x=>x.BaiduLongtitute);
            TempData["centerY"] = infrastructure.CellList.Average(x=>x.BaiduLattitute);
            return View(field);
        }

        public ActionResult ExportKml(string fieldName,
            EvaluationInfrastructure infrastructure,
            StatValueFieldRepository repository)
        {
            StatValueField field = repository.FieldList[(int)fieldName.GetStatValueIndex()];
            if (field.IntervalList.Count == 0)
            {
                TempData["warning"] = "显示区间设置为空！请先设置区间。";
                return RedirectToAction("PointsAnalysis");
            }

            GoogleKml kml = new GoogleKml("framework.xml");
            string absoluFilePath
                = Path.Combine(AppDomain.CurrentDomain.BaseDirectory + "uploads\\", 
                "Kmlresults-" + field.FieldName + DateTime.Today.ToString("yyyyMMdd"));
            kml.GenerateKmlFile(absoluFilePath, 
                infrastructure.Region.GetMeasureInfoList(field, EvaluationSettings.DistanceInMeter), field);
            return File(new FileStream(absoluFilePath, FileMode.Open),
                "application/octet-stream", Server.UrlEncode(
                "Kmlresults-" + field.FieldName + DateTime.Today.ToString("yyyyMMdd") + ".kml"));
        }

        public JsonResult ImportCells(EvaluationInfrastructure infrastructure, 
            string message)
        {
            IEnumerable<ENodeb> eNodebs;
            if (message != "")
            {
                string[] ids = message.GetSplittedFields(',');
                eNodebs
                    = from a in eNodebList
                      join b in ids
                      on a.ENodebId equals int.Parse(b)
                      select a;
            }
            else
            {
                eNodebs = eNodebList;
            }
            IEnumerable<IOutdoorCell> outdoorCellList = cellRepository.Query(eNodebs);

            infrastructure.AddCells(outdoorCellList as IEnumerable<EvaluationOutdoorCell>);

            return Json(infrastructure.CellList.Select(x =>
                new
                {
                    CellName = x.CellName,
                    CellInfo = x.Info()
                }).ToArray(),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult ImportCellsWithRange(EvaluationInfrastructure infrastructure,
            StatComplexFieldRepository repository,
            string fieldName, double southWestLon, double southWestLat,
            double northEastLon, double northEastLat)
        {
            infrastructure.ImportCellList(
                eNodebRepository, 
                cellRepository,
                new GeoPoint(southWestLon - GeoMath.BaiduLongtituteOffset, southWestLat - GeoMath.BaiduLattituteOffset),
                new GeoPoint(northEastLon - GeoMath.BaiduLongtituteOffset, northEastLat - GeoMath.BaiduLattituteOffset));
            if (string.IsNullOrEmpty(fieldName))
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
            infrastructure.Region.CalculatePerformance(EvaluationSettings.TrafficLoad);
            StatValueField field = repository.FieldList[(int)fieldName.GetStatValueIndex()];

            List<MeasurePointInfo> infoList
                = infrastructure.Region.GetMeasureMergedList(field, EvaluationSettings.DistanceInMeter);
            return Json(infoList.Select(x =>
                new
                {
                    X1 = x.X1 + GeoMath.BaiduLongtituteOffset,
                    Y1 = x.Y1 + GeoMath.BaiduLattituteOffset,
                    X2 = x.X2 + GeoMath.BaiduLongtituteOffset,
                    Y2 = x.Y2 + GeoMath.BaiduLattituteOffset,
                    C = x.ColorString
                }).ToArray(),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCells(EvaluationInfrastructure infrastructure)
        {
            return Json(infrastructure.CellList.Select(x =>
                new
                {
                    CellName = x.CellName,
                    CellInfo = x.Info()

Lte.WebApp/Views/Home/Infrastructure.cshtml
@{
    ViewBag.Title = "基础数据管理";
    ViewBag.Message = "——LTE、CDMA基础信息（包括DT、KPI、站点建设开通等方面的数据）";
}
@section featured {
    <hgroup class="title">
        <h1>@ViewBag.Title.</h1>
        <h2>@ViewBag.Message</h2>
    </hgroup>
    <p>
        在这里，我们提供<em>基础数据完整化</em>功能。
    </p>
}
<div class="row">
    <div class="col-md-4">
        <div class="one">
            <h4>建设交维信息</h4>
            
        </div>
    </div>
    <div class="col-md-4">
        <div class="two">
            <h4>日常指标导入</h4>
            <p>
                导入全网指标监控日报（需用管理员帐号登录）请点击
                @Html.ActionLink("日常指标导入", "Import", "Kpi", null, new {@class="btn btn-primary"})<br/>
                <b>数据提供人：欧阳晖</b>
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="three">
            <h4>网优工参信息</h4>
            <p>
                全网小区列表和地理化显示
                @Html.ActionLink("LTE小区列表", "List", "Parameters", null, new {@class="btn btn-primary"})<br />
                对全网的基站按照基站名称、地址等信息进行查询，并进行个别基站小区的增删、修改信息的操作请点击
                @Html.ActionLink("LTE小区查询", "Query", "Parameters", null, new {@class="btn btn-primary"})<br/>
                <b>数据提供人：欧阳晖</b>
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="four">
            <h4>DT基础信息</h4>  
            <p>
                按照区域或专题查看已导入的DT基础信息
                @Html.ActionLink("DT数据查看","List","Dingli", null, new {@class="btn btn-primary"})<br />
                <b>数据提供人：韩亚妹</b>
            </p>     
        </div>
    </div>
</div>

Lte.WebApp/Views/Home/Manage.cshtml
@{
    ViewBag.Title = "后台数据管理";
    ViewBag.Message = "——基础信息导入管理、本网页联系人信息";
}
@section featured {
    <hgroup class="title">
        <h1>@ViewBag.Title.</h1>
        <h2>@ViewBag.Message</h2>
    </hgroup>
    <p>
        在这里，我们为数据管理人员提供小规模的数据录入功能（大量的数据录入需要使用应用程序）
    </p>
}
<h3>我们提供以下功能：</h3>
<div class="row">
    <div class="col-md-4">
        <div class="one">
            <h4>行政区域管理</h4>
            <p>
                对全网的地市、区域和镇区信息的增删、查询请点击
                @Html.ActionLink("行政区域管理", "Region", "Region") 
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="two">
            <h4>校园网基本信息导入</h4>
            <p>
                
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="three">
            <h4>日常指标导入</h4>
            <p>
                对全网分片区的2G、3G忙时KPI指标的导入请点击
                @Html.ActionLink("日常忙时指标导入", "Import", "KPI")
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="four">
            <h4>联系人信息</h4>
            <p>
                本网页的系统支持信息请点击
                @Html.ActionLink("技术支持信息", "Contact", "Manage")
            </p>        
        </div>
    </div>
</div>

Lte.WebApp/Views/Home/Topic.cshtml
@{
    ViewBag.Title = "专题优化";
    ViewBag.Message = "——提供全方位的覆盖评估场景和专题规划和优化工具";
}

@section featured {
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                在这里，我们提供<em>专题优化精品化</em>的功能，更多精彩内容请点击以下各个菜单项。
            </p>
}

<div class="row">
    <div class="col-md-4">
        <div class="one">
            <h4>小区覆盖仿真模拟</h4>
            根据各小区的工程参数模拟覆盖范围，主要覆盖指标（RSRP、SINR）进行分析和呈现请点击 
            @Html.ActionLink("开始仿真", "RegionDef", "Evaluation", null, new {@class="btn btn-primary"})
        </div>
    </div>
    <div class="col-md-4">
        <div class="two">
            <h4>LTE“一减”专题分析</h4>
            分析3G的RU数据和CDR数据，挖掘小区的重叠覆盖、过覆盖等问题，对4G共站的效果进行模拟，并在百度地图上呈现。
            @Html.ActionLink("小区分析", "Import", "Rutrace", null, new {@class="btn btn-primary"})
        </div>
    </div>
    <div class="col-md-4">
        <div class="three">
            <h4>校园网专题优化</h4>
            校园网专项优化，包括数据管理、指标分析和覆盖呈现<br/>
            校园网地图一览：
            @Html.ActionLink("校园网一览","Map","College", null, new {@class="btn btn-primary"})<br/>
            校园网详细信息管理：
            @Html.ActionLink("校园网信息","List","College", null, new {@class="btn btn-primary"})
        </div>
    </div>    
    <div class="col-md-4">
        <div class="four">
            <h4>指标监控分析</h4>
            对日常指标的监控请点击
            @Html.ActionLink("日常指标监控", "Index", "Kpi", null, new {@class="btn btn-primary"})
            ，全天TOP掉话分析请点击
            @Html.ActionLink("TOP掉话", "TopDrop2GDaily", "Kpi", null, new {@class="btn btn-primary"})
        </div>
    </div>    
    <div class="col-md-4">
        <div class="five">
            <h4>4G指标分析</h4>
            精确覆盖率指标分析和地理化呈现请点击
            @Html.ActionLink("4G精确覆盖率", "Precise4G", "Kpi", null, 
            new {@class="btn btn-primary", @title="统计日常的4G精确覆盖率指标"})
        </div>
    </div>
</div>