Lte.WebApp/Controllers/Kpi/KpiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lte.Evaluations.Kpi;
using Lte.Evaluations.ViewHelpers;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;
using Lte.Parameters.Kpi.Abstract;
using Lte.Parameters.Kpi.Entities;
using Lte.Parameters.Kpi.Service;
using Lte.Parameters.Service.Region;

namespace Lte.WebApp.Controllers.Kpi
{
    public class KpiController : Controller, IKpiImportController
    {
        private readonly IRegionRepository regionRepository;
        private readonly ITownRepository townRepository;
        private readonly ITopCellRepository<CdmaRegionStat> cdmaStatRepository;
        private readonly ITopCellRepository<TopDrop2GCell> topDrop2GRepository;
        public SaveTimeCityKpiStatsService<TopDrop2GCell, TopDrop2GCellExcel> SaveTimeKpiStatsService { get; set; }
        private readonly ITopCellRepository<TopDrop2GCellDaily> topDrop2GDailyRepository;
        private readonly ITopCellRepository<TopConnection3GCell> topConnection3GRepository;
        private readonly ITopCellRepository<TownPreciseCoverage4GStat> townPrecise4GRepository;
        public SaveTimeCityKpiStatsService<TopConnection3GCell, TopConnection3GCellExcel> Save3GStatsService { get; set; }
        private readonly IBtsRepository btsRepository;
        private readonly IENodebRepository eNodebRepository;
        private readonly QueryNamesService regionNamesService;
        private readonly QueryNamesService districtNamesService;

        public KpiController(IRegionRepository regionRepository,
            ITownRepository townRepository,
            ITopCellRepository<CdmaRegionStat> cdmaStatRepository,
            ITopCellRepository<TopDrop2GCell> topDrop2GRepository,
            ITopCellRepository<TopDrop2GCellDaily> topDrop2GDailyRepository,
            ITopCellRepository<TopConnection3GCell> topConnection3GRepository,
            ITopCellRepository<TownPreciseCoverage4GStat> townPrecise4GRepository,
            IBtsRepository btsRepository,
            IENodebRepository eNodebRepository)
        {
            this.regionRepository = regionRepository;
            this.townRepository = townRepository;
            this.cdmaStatRepository = cdmaStatRepository;
            this.topDrop2GRepository = topDrop2GRepository;
            
            this.topDrop2GDailyRepository = topDrop2GDailyRepository;
            this.topConnection3GRepository = topConnection3GRepository;
            
            this.townPrecise4GRepository = townPrecise4GRepository;
            this.btsRepository = btsRepository;
            this.eNodebRepository = eNodebRepository;

            this.Initialize(topDrop2GRepository, topConnection3GRepository);
            regionNamesService = new QueryRegionCityNamesService(this.regionRepository.GetAll());
            districtNamesService = new QueryDistinctDistrictNamesService(this.townRepository.GetAll());
        }

        public ActionResult Index(KpiListViewModel postedModel)
        {
            IEnumerable<CdmaRegionStat> stats 
                = cdmaStatRepository.Stats.ToList().GetLastDateStats(
                regionRepository.GetAllList(), postedModel.StatDate);
            DateTime endDate = (stats.Any()) ? 
                stats.First().StatDate : DateTime.Today.AddDays(-1);
            KpiListViewModel viewModel = new KpiListViewModel
            {
                CdmaStats = stats,
                EndDate = endDate,
                StatDate = endDate,
                StartDate = endDate.AddDays(-7),
                Cities = regionNamesService.Query().ToList()
            };
            return View(viewModel);
        }

        public ActionResult Precise4G(KpiListViewModel postedModel)
        {
            IEnumerable<TownPrecise4GView> stats
                = townPrecise4GRepository.Stats.GetLastDateStats(
                townRepository.GetAllList(), postedModel.StatDate);
            DateTime endDate = (stats.Any()) ?
                stats.First().StatDate : DateTime.Today.AddDays(-1);
            Precise4GViewModel viewModel = new Precise4GViewModel
            {
                EndDate = endDate,
                StatDate = endDate,
                StartDate = endDate.AddDays(-7),
                PreciseStats = stats,
                Districts = districtNamesService.Query()
            };
            return View(viewModel);
        }

        public ViewResult TopDrop2G(TopDrop2GViewModel postedModel)
        {
            TopDrop2GViewModel viewModel 
                = topDrop2GRepository.Stats.GenerateView<TopDrop2GViewModel, TopDrop2GCell, TopDrop2GCellView>(
                postedModel.StatDate, regionNamesService.Query().ToList(),
                btsRepository.GetAllList(), eNodebRepository.GetAllList());
            return View(viewModel);
        }

        public ViewResult TopDrop2GDaily(TopDrop2GDailyViewModel postedModel)
        { 
            TopDrop2GDailyViewModel viewModel
                =topDrop2GDailyRepository.Stats.GenerateView<
                TopDrop2GDailyViewModel,TopDrop2GCellDaily,TopDrop2GCellDailyView>(
                postedModel.StatDate, regionNamesService.Query().ToList(),
                btsRepository.GetAllList(), eNodebRepository.GetAllList());
            return View(viewModel);
        }

        public ViewResult TopConnection3G(TopConnection3GViewModel postedModel)
        {
            TopConnection3GViewModel viewModel
                = topConnection3GRepository.Stats.GenerateView<
                TopConnection3GViewModel, TopConnection3GCell, TopConnection3GCellView>(
                postedModel.StatDate, regionNamesService.Query().ToList(),
                btsRepository.GetAllList(), eNodebRepository.GetAllList());
            return View(viewModel);
        }

        [Authorize]
        public ViewResult Import()
        {
            return View();
        }

        [Authorize]
        public ViewResult KpiImport()
        {
            QueryNamesService regionService = new QueryOptimizeRegionNamesService(regionRepository.GetAll());
            string[] sheetNames = regionService.Query().ToArray();

            HttpPostedFileBase httpPostedFileBase = Request.Files["dailyKpi"];
            if (httpPostedFileBase == null || httpPostedFileBase.FileName == "")
            {
                TempData["error"] = "请选择需要导入的Excel文件！";
                return View("Import");
            }

            KpiImportResult result = this.Import(httpPostedFileBase, sheetNames, regionRepository, cdmaStatRepository);

            TempData["success"] 
                = "成功保存区域指标：" + result.RegionStatsSaved + "条"
                  + "    成功保存TOP掉话指标" + result.TopDrop2GSaved + "条"
                  + "    成功保存TOP连接失败指标" + result.TopConnection3GSaved + "条";
            return View("Import");
        }
	}
}

Lte.WebApp/Controllers/Kpi/KpiStatController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Lte.Parameters.Kpi.Abstract;
using Lte.Parameters.Kpi.Entities;

namespace Lte.WebApp.Controllers.Kpi
{
    public class KpiStatController : Controller
    {
        private readonly ITopCellRepository<CdmaRegionStat> cdmaStatRepository;

        public KpiStatController(ITopCellRepository<CdmaRegionStat> cdmaStatRepository)
        {
            this.cdmaStatRepository = cdmaStatRepository;
        }

        public JsonResult Query(DateTime begin, DateTime end, AllCdmaDailyStatList statList)
        {
            statList.Import(cdmaStatRepository, begin, end);
            return Json(statList.Stats.Count, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDateCategories(string city, AllCdmaDailyStatList statList)
        {
            return Json(statList.DateCategories(city), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCityErlang2GSeries(string city, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetSummaryStats(x => x.ErlangExcludingSwitch);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCityDrop2GRateSeries(string city, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetSummaryStats(x => x.Drop2GRate * 100);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCityEcio2GSeries(string city, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetSummaryStats(x => x.Ecio * 100);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCityFlow3GSeries(string city, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetSummaryStats(x => x.Flow / 1024);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCityDownSwitchRateSeries(string city, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetSummaryStats(x => x.DownSwitchRate);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCityCi3GSeries(string city, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetSummaryStats(x => x.Ci * 100);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionErlang2GSeries(string city, string region, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetRegionStats(
                x => x.ErlangExcludingSwitch, x => x.Region, region);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionDrop2GRateSeries(string city, string region, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetRegionStats(
                x => x.Drop2GRate * 100, x => x.Region, region);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionEcio2GSeries(string city, string region, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetRegionStats(
                x => x.Ecio * 100, x => x.Region, region);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionFlow3GSeries(string city, string region, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetRegionStats(
                x => x.Flow / 1024, x => x.Region, region);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionCi3GSeries(string city, string region, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetRegionStats(
                x => x.Ci * 100, x => x.Region, region);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionDownSwitchRateSeries(string city, string region, AllCdmaDailyStatList statList)
        {
            IEnumerable<double> stats = statList.Stats[city].GetRegionStats(
                x => x.DownSwitchRate, x => x.Region, region);
            return Json(stats, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionList(string city, AllCdmaDailyStatList statList)
        {
            IEnumerable<string> regions = statList.Stats[city].Regions;
            return Json(regions, JsonRequestBehavior.AllowGet);
        }
	}
}

Lte.WebApp/Controllers/Kpi/LteStatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using Lte.Evaluations.Service;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;
using Lte.Parameters.Kpi.Abstract;
using Lte.Parameters.Kpi.Entities;

namespace Lte.WebApp.Controllers.Kpi
{
    public class QueryLteStatController : ApiController
    {
        private readonly ITopCellRepository<TownPreciseCoverage4GStat> lteStatRepository;
        private readonly IEnumerable<Town> towns;

        public QueryLteStatController(ITopCellRepository<TownPreciseCoverage4GStat> lteStatRepository,
            ITownRepository townRepository)
        {
            this.lteStatRepository = lteStatRepository;
            towns = townRepository.GetAllList();
        }

        [Route("api/QueryLteStat/{begin}/{end}")]
        public int Get(DateTime begin, DateTime end)
        {
            DateTime beginDate = end.AddDays(-200);
            DateTime endDate = end.AddDays(1);
            KpiStatContainer.AllLteDailyStatList = new AllLteDailyStatList(towns)
            {
                Stats = new Dictionary<string, DailyStatList<RegionPrecise4GStat>>()
            };
            IEnumerable<TownPreciseCoverage4GStat> stats = lteStatRepository.Stats.Where(
                x => x.StatTime > beginDate && x.StatTime < endDate).ToList();
            IEnumerable<RegionPrecise4GStat> items =
                stats.Select(x => new RegionPrecise4GStat(new TownPrecise4GView(x, towns)));
            KpiStatContainer.AllLteDailyStatList.Import(items, begin, end);
            return KpiStatContainer.AllLteDailyStatList.Stats.Count;
        }
    }

    public class QueryLteDistrictDatesController : ApiController
    {
        [Route("api/QueryLteDistrictDates/{district}")]
        public IEnumerable<string> Get(string district)
        {
            return KpiStatContainer.AllLteDailyStatList.DateCategories(district);
        }

        [Route("api/QueryLteDistrictDates")]
        public IEnumerable<string> Get()
        {
            return KpiStatContainer.AllLteDailyStatList.OverallDates;
        }
    }

    public class QueryLteMrsController : ApiController
    {
        [Route("api/QueryLteMrs/{district}")]
        public IEnumerable<int> Get(string district)
        {
            return KpiStatContainer.AllLteDailyStatList.Stats[district].GetSummaryStats(x => x.TotalMrs).ToList();
        }

        [Route("api/QueryLteMrs/{district}/{town}")]
        public IEnumerable<int> Get(string district, string town)
        {
            return KpiStatContainer.AllLteDailyStatList.Stats[district].GetRegionStats(
                x => x.TotalMrs, x => x.Region, town);
        }
    }

    public class QueryLteMrTableController : ApiController
    {
        [Route("api/QueryLteMrTable/{district}")]
        public IEnumerable<int> Get(string district)
        {
            return KpiStatContainer.AllLteDailyStatList.GetDistrictMrs(district);
        }
    }

    public class QueryPreciseRatesController : ApiController
    {
        [Route("api/QueryPreciseRates/{district}")]
        public IEnumerable<double> Get(string district)
        {
            return KpiStatContainer.AllLteDailyStatList.Stats[district].GetSummaryStats(
                x => x.PreciseRate * 100).ToList();
        }

        [Route("api/QueryPreciseRates/{district}/{town}")]
        public IEnumerable<double> Get(string district, string town)
        {
            return KpiStatContainer.AllLteDailyStatList.Stats[district].GetRegionStats(
                x => x.PreciseRate * 100, x => x.Region, town);
        }
    }

    public class QueryPreciseRateTableController : ApiController
    {
        [Route("api/QueryPreciseRateTable/{district}")]
        public IEnumerable<double> Get(string district)
        {
            return KpiStatContainer.AllLteDailyStatList.GetDistrictRates(district);
        }
    }

    public class QueryLteKpiTownListController : ApiController
    {
        [Route("api/QueryLteKpiTownList/{district}")]
        public IEnumerable<string> Get(string district)
        {
            return KpiStatContainer.AllLteDailyStatList.Stats[district].Regions;
        }
    }

    public class QueryPreciseStatController : ApiController
    {
        private readonly ITopCellRepository<PreciseCoverage4G> _repository;

        public QueryPreciseStatController(ITopCellRepository<PreciseCoverage4G> repository)
        {
            _repository = repository;
        }

        [Route("api/QueryPreciseStat/{cellId}/{sectorId}/{date}")]
        public IEnumerable<PreciseCoverage4G> Get(int cellId, byte sectorId, DateTime date)
        {
            DateTime begin = date.AddDays(-7);
            DateTime end = date.AddDays(7);
            return _repository.Stats.Where(x =>
                x.StatTime >= begin && x.StatTime <= end
                && x.CellId == cellId && x.SectorId == sectorId).ToList();
        }

        public IEnumerable<PreciseCoverage4G> Get(int cellId, byte sectorId, DateTime begin, DateTime end)
        {
            return _repository.Stats.Where(x =>
                x.StatTime >= begin && x.StatTime <= end
                && x.CellId == cellId && x.SectorId == sectorId).ToList();
        }
    }
}

Lte.WebApp/Views/Kpi/Import.cshtml
@{
    ViewBag.Title = "指标统计数据导入";
    ViewBag.Message = "——读取Excel表信息，然后导入数据库";
}

@section featured {
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
}
<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("KpiImport", "Kpi",
            FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <fieldset>
                <legend>指标文件选择</legend>
                <ol>
                    <li>
                        每日KPI Excel文件选择：
                        <input type="file" name="dailyKpi" accept=".xls, .xlsx" />
                    </li>
                </ol>
            </fieldset>

            <p>
                <button type="submit" class="btn btn-primary btn-lg">
                    <span class="glyphicon glyphicon-save"></span>导入文件
                </button>
            </p>
        }
    </div>
    <div class="col-md-4">
        @{ Html.RenderPartial("_KpiMenu");}
    </div>
</div>

Lte.WebApp/Views/Kpi/Index.cshtml
@model Lte.Evaluations.Kpi.KpiListViewModel

@{
    ViewBag.Title = "全网指标总览";
}

@section featured {
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
            </hgroup>
    }

<div class="row">
    <div class="col-md-8">
        <ul id="radiotabs" class="nav nav-tabs">
            <li class="active"><a href ="#overall" data-toggle="tab">总体指标情况</a></li>
            @foreach (string city in Model.Cities)
            {
                <li><a href="#chart-@city" data-toggle="tab">@city 指标变化趋势图表</a></li>
            }
        </ul>
        <div id="myTabContent" class="tab-content">
            <div id="overall" class="tab-pane fade in active">
                @using (Html.BeginForm("Index", "Kpi",
                    FormMethod.Post, new { enctype = "multipart/form-data" }))
                { 
                    Html.RenderPartial("_StatDateSelection",Model);
                    <p>
                        <button type="submit" id="stat" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-user"></span>统计指标

                        </button>

                    </p>
                }
                @if (Model.CdmaStats.Any())
                {
                    Html.RenderPartial("_OverallStatTable", Model.CdmaStats);
                }
            
            </div>
            @foreach (string city in Model.Cities)
            { 
                <div id="chart-@city" class="tab-pane fade">
                    @{ Html.RenderPartial("_DateSpanSelection", Model); }
                    <p>
                        <button type="button" id="showresults" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-search"></span>显示图表
                        </button>
                    </p>   
                    <div id="display-@city"> 
                        <h3><a href="#">2G话务量</a></h3>       
                        <div id="erlang-2G-@city" style="min-height: 400px; margin: 0 auto"></div>
                        <h3><a href="#">2G掉话率</a></h3> 
                        <div id="drop-2G-@city" style="min-height: 400px; margin: 0 auto"></div>
                        <h3><a href="#">Ec/Io优良比</a></h3> 
                        <div id="ecio-2G-@city" style="min-height: 400px; margin: 0 auto"></div>
                        <h3><a href="#">3G流量</a></h3> 
                        <div id="flow-3G-@city" style="min-height: 400px; margin: 0 auto"></div>
                        <h3><a href="#">3G下切2G流量比</a></h3> 
                        <div id="downswitch-@city" style="min-height: 400px; margin: 0 auto"></div>
                        <h3><a href="#">C/I优良比</a></h3> 
                        <div id="ci-3G-@city" style="min-height: 400px; margin: 0 auto"></div>
                    </div>             
                </div>
            }
        </div>
    </div>
    <div class="col-md-4">
        @{ Html.RenderPartial("_KpiMenu");}
    </div>
    @foreach (string city in Model.Cities)
    { 
        <input type="hidden" class="citylist" value="@city" />
    }
</div>

@section css
{
    @Styles.Render("~/Content/themes/base/css")
}
@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/highcharts")
@Scripts.Render("~/bundles/jqueryui")
<script type="text/javascript" src="~/Scripts/Dingli/ComboSetting.js"></script>
<script type="text/javascript" src="~/Scripts/Highcharts/modules/exporting.js"></script>
<script type="text/javascript" src="~/Scripts/Parameters/KpiStatSet.js"></script>
<script type="text/javascript" src="~/Scripts/Parameters/DateValidation.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#StatDate").datepicker({ dateFormat: 'yy-mm-dd' });
            $("#StartDate").datepicker({ dateFormat: 'yy-mm-dd' });
            $("#EndDate").datepicker({ dateFormat: 'yy-mm-dd' });
            $(".citylist").each(function () {
                $("#display-" + $(this).val()).accordion();
            });
        });
        $("#showresults").click(function () {
            var validation = new DateValidation({
                startdatetag: "StartDate",
                enddatetag: "EndDate",
                messagetag: "system_message"
            });
            if (validation.validate()) {
                $.ajax({
                    url: "/KpiStat/Query",
                    type: "GET",
                    dataType: "json",
                    data: {
                        begin: $("#StartDate").val(),
                        end: $("#EndDate").val()
                    },
                    success: function () {
                        $(".citylist").each(function () {
                            var city = $(this).val();
                            $.ajax({
                                url: "/KpiStat/GetDateCategories",
                                type: "GET",
                                dataType: "json",
                                data: {
                                    city: city
                                },
                                success: function (data) {
                                    $("#display-" + city + " > h3 a").each(function() {
                                        var setting = new ComboSetting(city + $(this).html() + '变化趋势');
                                        var dataSet = new KpiStatSet(setting);
                                        dataSet.generateChart(city, data, $(this).parent().next(), $(this).html());
                                    });
                                }
                            });
                        });
                    }
                });
            }
        });
    </script>
}

Lte.WebApp/Views/Kpi/TopConnection3G.cshtml
@model Lte.Evaluations.Kpi.TopConnection3GViewModel

@{
    ViewBag.Title = "TOP连接小区分析";
}

@section featured {
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
            </hgroup>
    }
<div class="row">
    <div id="radiotabs" class="col-md-8">
        <ul>
            <li><a href ="#oneday">当日指标分析</a></li>
            <li><a href="#multi-days">TOP小区变化趋势</a></li>
        </ul>
        <div id="oneday">
            @using (Html.BeginForm("TopConnection3G", "Kpi",
                FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                Html.RenderPartial("_StatDateSelection", Model);
                <p><input type="submit" id="stat" value="统计指标" /></p>
            }
            @if (Model.StatList.Any())
            {
                <h3>@Model.StatDate.ToShortDateString() TOP连接指标</h3>
                Html.RenderPartial("_TopConnection3GStatTable", Model.StatList);
            }
        </div>
        <div id="multi-days">
            @{ Html.RenderPartial("_DateSpanAndTopCountSelection", Model); }
            <p><input type="button" id="showresults" value="显示图表" /></p>
            @foreach (string city in Model.Cities)
            { 
                <div id="top-@city" style="min-width: 600px; min-height: 400px; margin: 0 auto"></div>
            }
        </div>
    </div>
    <div class="col-md-4">@{ Html.RenderPartial("_KpiMenu");}</div>
    @foreach (string city in Model.Cities)
    { 
        <input type="hidden" class="citylist" value="@city" />
    }
    <div id="dialog-modal"></div>
</div>

@section css{
@Styles.Render("~/Content/themes/base/css")
}

@section Scripts {
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/highcharts")
<script type="text/javascript" src="~/Scripts/Highcharts/modules/exporting.js"></script>
<script type="text/javascript" src="~/Scripts/Dingli/ComboSetting.js"></script>
<script type="text/javascript" src="~/Scripts/Parameters/TopStatSet.js"></script>
<script type="text/javascript" src="~/Scripts/Parameters/TopHistorySet.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#radiotabs").tabs();
        $("#StatDate").datepicker({ dateFormat: 'yy-mm-dd' });
        $("#StartDate").datepicker({ dateFormat: 'yy-mm-dd' });
        $("#EndDate").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $("#showresults").click(function () {
        var begin = new Date($("#StartDate").val());
        var end = new Date($("#EndDate").val());
        $("#system_message").html("");
        if (begin.toString() == "Invalid Date" || end.toString() == "Invalid Date") {
            $("#system_message").append("<div class='error'>输入日期格式错误！</div>");
        } else if (begin > end) {
            $("#system_message").append("<div class='error'>开始日期必须早于或等于结束日期！</div>");
        } else {
            $(".citylist").each(function () {
                var city = $(this).val();
                var statSet = new TopStatSet(city);
                statSet.queryTopConnection3G($("#StartDate").val(), $("#EndDate").val(), "#top-", $("#TopCounts").val());
            });
        }
    });
    $(".topdetails").click(function () {
        var cellInfo = $(this).attr('name');
        var end = $("#StatDate").val();
        var setting = new TopHistorySet(cellInfo, end);

        $("#dialog-modal").dialog({
            modal: true,
            title: '历史信息',
            hide: 'slide',
            width: 640,
            height: 480,
            buttons: {
                '关闭': function () {
                    $(this).dialog("close");
                }
            },
            open: function () {
                $(this).html("");
                $(this).highcharts(setting.getTopConnection3GOptions());
            }
        });
    });
</script>
}

Lte.WebApp/Views/Kpi/_DateSpanAndTopCountSelection.cshtml
@model Lte.Evaluations.Kpi.IDateSpanAndTopCountViewModel

<h4>日期选择</h4>
<div class="input-group">
    <span class="input-group-addon">@Html.LabelFor(x => x.StartDate)</span>
    @Html.EditorFor(x => x.StartDate, new {@class="form-control"})
</div>
<div class="input-group">
    <span class="input-group-addon">@Html.LabelFor(x => x.EndDate)</span>
    @Html.EditorFor(x => x.EndDate, new {@class="form-control"})
</div>
<div class="input-group">
    <span class="input-group-addon">@Html.LabelFor(x=>x.TopCounts)</span>
    @Html.EditorFor(x=>x.TopCounts, new {@class="form-control"})
</div>

Lte.WebApp/Views/Kpi/_DateSpanSelection.cshtml
@model Lte.Evaluations.Kpi.IDateSpanViewModel

<h4>日期选择：</h4>
<div class="input-group">
    <span class="input-group-addon">@Html.LabelFor(x => x.StartDate)</span>
    @Html.EditorFor(x => x.StartDate, new {@class="form-control"})
</div>
<div class="input-group">
    <span class="input-group-addon">@Html.LabelFor(x => x.EndDate)</span>
    @Html.EditorFor(x => x.EndDate, new {@class="form-control"})
</div>

Lte.WebApp/Views/Kpi/_KpiMenu.cshtml
    <div class="list-group">
        <div class="list-group-item active">
            <h3 class="list-group-item-heading">指标统计相关功能</h3>
        </div>
        @Html.ActionLink("全网基本指标", "Index", null, new{@class="list-group-item"})
        @Html.ActionLink("全网4G指标", "Precise4G", null, new{@class="list-group-item"})
        @Html.ActionLink("TOP-2G掉话指标分析", "TopDrop2G", null, new{@class="list-group-item"})
        @Html.ActionLink("TOP-2G全天掉话指标分析", "TopDrop2GDaily", null, new{@class="list-group-item"})
        @Html.ActionLink("TOP-3G连接指标分析", "TopConnection3G", null, new{@class="list-group-item"})
        @Html.ActionLink("日常指标导入", "Import", null, new{@class="list-group-item"})
    </div>