Lte.WebApp/Controllers/Dt/CoverageController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lte.Domain.Geo.Service;
using Lte.Domain.LinqToCsv.Context;
using Lte.Domain.LinqToCsv.Description;
using Lte.Evaluations.Abstract;
using Lte.Evaluations.Dingli;
using Lte.Evaluations.Entities;
using Lte.Evaluations.Service;
using Lte.Evaluations.ViewHelpers;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;
using Lte.Parameters.Service.Coverage;

namespace Lte.WebApp.Controllers.Dt
{
    public class CoverageController : Controller
    {
        private readonly IENodebRepository eNodebRepository;
        private readonly ICellRepository cellRepository;

        public CoverageController(IENodebRepository eNodebRepository,
            ICellRepository cellRepositroy)
        {
            this.eNodebRepository = eNodebRepository;
            cellRepository = cellRepositroy;
        }

        public JsonResult CoverageAdjust(CoverageStatChart chart)
        {
            List<ENodeb> eNodebList = eNodebRepository.GetAllList();
            IEnumerable<CoverageAdjustment> adjustments =
                chart.StatList.GenerateAdjustmentList(cellRepository, eNodebList);
            var result = from a in adjustments
                         join e in eNodebList
                         on a.ENodebId equals e.ENodebId
                         select new
                         {
                             N = e.Name + "-" + a.SectorId,
                             F = a.Frequency,
                             F165m = (int)(100 * a.Factor165m) / (double)(100),
                             F135m = (int)(100 * a.Factor135m) / (double)(100),
                             F105m = (int)(100 * a.Factor105m) / (double)(100),
                             F75m = (int)(100 * a.Factor75m) / (double)(100),
                             F45m = (int)(100 * a.Factor45m) / (double)(100),
                             F15m = (int)(100 * a.Factor15m) / (double)(100),
                             F15 = (int)(100 * a.Factor15) / (double)(100),
                             F45 = (int)(100 * a.Factor45) / (double)(100),
                             F75 = (int)(100 * a.Factor75) / (double)(100),
                             F105 = (int)(100 * a.Factor105) / (double)(100),
                             F135 = (int)(100 * a.Factor135) / (double)(100),
                             F165 = (int)(100 * a.Factor165) / (double)(100)
                         };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CoverageIntervalPercentage(string fieldName, CoverageStatChart chart)
        {
            StatValueField field = new StatValueField { FieldName = fieldName };
            field.AutoGenerateIntervals(8);
            IEnumerable<double> values = (fieldName == "信号RSRP") ?
                chart.StatList.Select(x => x.Rsrp) : chart.StatList.Select(x => x.Sinr);
            Dictionary<string, double> result = field.GetPercentageStat(values);
            return Json(result.Select(x => new { N = x.Key, V = 100 * x.Value }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ExportPoints(string fieldName, StatValueFieldRepository repository,
            CoverageStatChart chart)
        {
            if (chart.StatList.Count == 0)
            {
                TempData["warning"] = "覆盖数据为空，请先导入数据分析。";
                return RedirectToAction("CoverageImport");
            }
            StatValueField field = repository.GenerateDefaultField(fieldName);
            TempData["centerX"] = chart.StatList.Average(x=>x.BaiduLongtitute);
            TempData["centerY"] = chart.StatList.Average(x=>x.BaiduLattitute);
            return View(field);
        }

        public JsonResult GetStatValueField(StatValueFieldRepository repository,
            string fieldName)
        {
            StatValueField field = repository.GenerateDefaultField(fieldName);
            return Json(field.IntervalList.Select(x => new
            {
                L = x.IntervalLowLevel,
                H = x.IntervalUpLevel,
                C = x.Color.ColorStringForHtml,
                K = x.Color.ColorStringForKml
            }).ToArray(),
            JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCoveragePoints(string fieldName,
            StatValueFieldRepository repository, CoverageStatChart chart)
        {
            StatValueField field = repository.GenerateDefaultField(fieldName);
            return Json(chart.StatList.Select(x => new
            {
                X = x.Longtitute + GeoMath.BaiduLongtituteOffset,
                Y = x.Lattitute + GeoMath.BaiduLattituteOffset,
                C = field.GetColor(fieldName == "信号RSRP" ? x.Rsrp : x.Sinr, "FFFFFF")
            }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult CoverageImport()
        {
            TempData["StatLength"] = 0;
            return View();
        }

        public ActionResult CoverageAnalyze(HttpPostedFileBase[] fileUpload, CoverageStatChart chart)
        {
            List<CoverageStat> coverageStatList = new List<CoverageStat>();
            if (fileUpload[0] != null)
            {
                foreach (HttpPostedFileBase file in fileUpload)
                {
                    using (HttpFileImporter importer = new HttpFileImporter(file))
                    {
                        if (!importer.Success)
                        {
                            if (TempData["warning"] == null)
                            {
                                TempData["warning"] = "请选择合适的路测数据导入！读取以下文件失败："
                                                      + importer.FilePath;
                            }
                            else
                            {
                                TempData["warning"] += "; " + importer.FilePath;
                            }
                        }
                        else
                        {
                            string extension = Path.GetExtension(importer.FileName);
                            if (extension != null)
                            {
                                string fileExt = extension.ToLower();
                                coverageStatList.AddRange(
                                    (fileExt == ".txt") ?
                                        CsvContext.Read<LogRecord>(
                                            importer.Reader, CsvFileDescription.TabDescription).Select(x =>
                                            {
                                                CoverageStat stat = new CoverageStat(); stat.Import(x); return stat;
                                            }).ToList() :
                                        CsvContext.Read<HugelandRecord>(
                                            importer.Reader, CsvFileDescription.CommaDescription).Select(x =>
                                            {
                                                CoverageStat stat = new CoverageStat(); stat.Import(x); return stat;
                                            }));
                            }
                            chart.Import(coverageStatList);
                            if (TempData["warning"] == null)
                            {
                                TempData["success"] = "导入路测数据成功！";
                            }
                        }
                    }
                }
            }

            ViewBag.Title = "路测覆盖指标分析";
            TempData["StatLength"] = chart.StatList.Count;
            return View("CoverageImport");
        }

        public ActionResult FileRecords2G(string fileName)
        {
            FileRecordsRepository.Update2GList(DCTestService.Query2GFileRecords(fileName).ToList());
            TestFileRecordsViewModel viewModel = new TestFileRecordsViewModel
            {
                CenterX = FileRecordsRepository.FileRecords2GList.Average(x => x.BaiduLongtitute),
                CenterY = FileRecordsRepository.FileRecords2GList.Average(x => x.BaiduLattitute),
                FileName = fileName
            };
            return View(viewModel);
        }

        public ActionResult FileRecords3G(string fileName)
        {
            FileRecordsRepository.Update3GList(DCTestService.Query3GFileRecords(fileName).ToList());
            TestFileRecordsViewModel viewModel = new TestFileRecordsViewModel
            {
                CenterX = FileRecordsRepository.FileRecords3GList.Average(x => x.BaiduLongtitute),
                CenterY = FileRecordsRepository.FileRecords3GList.Average(x => x.BaiduLattitute),
                FileName = fileName
            };
            return View(viewModel);
        }

        public ActionResult FileRecords4G(string fileName)
        {
            FileRecordsRepository.Update4GList(DCTestService.Query4GFileRecords(fileName).ToList());
            TestFileRecordsViewModel viewModel = new TestFileRecordsViewModel
            {
                CenterX = FileRecordsRepository.FileRecords4GList.Average(x => x.BaiduLongtitute),
                CenterY = FileRecordsRepository.FileRecords4GList.Average(x => x.BaiduLattitute),
                FileName = fileName
            };
            return View(viewModel);
        }
    }
}

Lte.WebApp/Controllers/Dt/DingliController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Lte.Domain.LinqToCsv.Context;
using Lte.Domain.LinqToCsv.Description;
using Lte.Evaluations.Dingli;
using Lte.Evaluations.ViewHelpers;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;
using Lte.Parameters.Service.Coverage;

namespace Lte.WebApp.Controllers.Dt
{
    public class DingliController : Controller
    {
        private static IEnumerable<Town> towns;

        public DingliController(ITownRepository townRepository)
        {
            LogRecordRepository.ThroughputCalculationDelay = 1;
            if (towns == null)
                towns = townRepository.GetAllList();
        }

        public ActionResult HandoverImport()
        {
            TempData["StatLength"] = 0;
            return View();
        }

        public ActionResult HandoverAnalyze()
        {
            using (HttpFileImporter importer = new HttpFileImporter(Request.Files["fileUpload"]))
            {
                if (!importer.Success)
                {
                    TempData["error"] = "请选择合适的路测数据导入！";
                }
                else
                {
                    LogRecordRepository recordRepository = new LogRecordRepository
                    {
                        LogRecordList = CsvContext.Read<LogRecord>(
                            new StreamReader(importer.FilePath), 
                            CsvFileDescription.TabDescription).ToList().Merge()
                    };
                    recordRepository.GetHandoverInfoList();

                    ViewBag.Title = "导入路测数据:" + importer.FileName;
                }
            }
            return View("HandoverImport");
        }

        public ActionResult ExportLogs(string fileName)
        {
            if (TempData["HandoverList"] == null) { return Redirect("HandoverImport"); }
            string absoluFilePath
                = Path.Combine(AppDomain.CurrentDomain.BaseDirectory + "uploads\\", fileName);
            CsvFileDescription fileDescription = CsvFileDescription.ChineseExportDescription;
            CsvContext.Write(TempData["HandoverList"] as List<HandoverInfo>, 
                absoluFilePath, fileDescription);
            return File(new FileStream(absoluFilePath, FileMode.Open),
                "application/octet-stream", Server.UrlEncode(fileName));
        }

        public ActionResult List()
        {
            TestListViewModel viewModel = new TestListViewModel
            {
                AreaTestDateList = DCTestService.QueryTestDateInfos().ToList(),
                TownList = towns
            };
            return View(viewModel);
        }

    }
}

Lte.WebApp/Controllers/Dt/RateController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Lte.Domain.LinqToCsv.Context;
using Lte.Domain.LinqToCsv.Description;
using Lte.Evaluations.Dingli;
using Lte.Evaluations.ViewHelpers;

namespace Lte.WebApp.Controllers.Dt
{
    public class RateController : Controller
    {
        public ActionResult RateImport()
        {
            ViewBag.Title = "导入路测数据";
            TempData["StatLength"] = 0;
            return View();
        }

        public ActionResult RateAnalyze(RateStatChart chart)
        {
            using (HttpFileImporter importer = new HttpFileImporter(Request.Files["fileUpload"]))
            {
                if (!importer.Success)
                {
                    TempData["error"] = "请选择合适的路测数据导入！";
                    ViewBag.Title = "导入路测数据";
                }
                else
                {
                    TempData["Path"] = importer.FilePath;
                    string extension = Path.GetExtension(importer.FileName);
                    if (extension != null)
                    {
                        string fileExt = extension.ToLower();
                        List<BasicRateStat> rateStatList
                            = (fileExt == ".txt") ?
                                CsvContext.Read<LogRecord>(
                                    importer.Reader, CsvFileDescription.TabDescription).ToList().MergeStat().Merge() :
                                CsvContext.Read<HugelandRecord>(
                                    importer.Reader, CsvFileDescription.CommaDescription).Select(
                                        x => x.Normalize()).ToList().MergeStat().Where(
                                            x => x.PdschRbRate > 0).Select(x => (BasicRateStat)x).ToList();
                        chart.Import(rateStatList);
                    }
                    ViewBag.Title = "路测速率指标分析";
                    TempData["success"] = "导入路测数据:" + importer.FileName + "成功！";
                }
            }
            TempData["StatLength"] = chart.StatList.Count;
            return View("RateImport");
        }

        public JsonResult GetPdschRbTimeSeries(RateStatChart chart)
        {
            return Json(chart.StatList.Select(x =>
                new { Time = x.PassedTimeInSeconds, RB = x.PdschRbRate }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDlFrequencyEfficiencyTimeSeries(RateStatChart chart)
        {
            return Json(chart.StatList.Select(x =>
                new { Time = x.PassedTimeInSeconds, FE = x.DlFrequencyEfficiency }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDlPdcpThroughputTimeSeries(RateStatChart chart)
        {
            return Json(chart.StatList.Select(x =>
                new { Time = x.PassedTimeInSeconds, TP = (double)x.DlThroughput / 1024 / 1024 }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRsrpTimeSeries(RateStatChart chart)
        {
            return Json(chart.StatList.Where(x => x.Rsrp > -150).Select(x =>
                new { Time = x.PassedTimeInSeconds, Rsrp = x.Rsrp }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSinrTimeSeries(RateStatChart chart)
        {
            return Json(chart.StatList.Where(x => x.Sinr > -30).Select(x =>
                new { Time = x.PassedTimeInSeconds, Sinr = x.Sinr }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLowRbRateSinrToFrequencyEfficiency(RateStatChart chart)
        {
            return Json(chart.StatList.Where(x => x.DlRbsPerSlot <= 5 && x.Sinr > -30).Select(x =>
                new { Sinr = x.Sinr, FE = x.DlFrequencyEfficiency }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetHighRbRateSinrToFrequencyEfficiency(RateStatChart chart)
        {
            return Json(chart.StatList.Where(x => x.DlRbsPerSlot > 5 && x.Sinr > -30).Select(x =>
                new { Sinr = x.Sinr, FE = x.DlFrequencyEfficiency }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTheorySinrToFrequencyEfficiency(RateStatChart chart)
        {
            return Json(chart.TheoryLine.Select(x =>new { Sinr = x.Key, FE = x.Value }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLowRbRateRsrpToFrequencyEfficiency(RateStatChart chart)
        {
            return Json(chart.StatList.Where(x => x.DlRbsPerSlot <= 5 && x.Rsrp > -150).Select(x =>
                new { Rsrp = x.Rsrp, FE = x.DlFrequencyEfficiency }),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetHighRbRateRsrpToFrequencyEfficiency(RateStatChart chart)
        {
            return Json(chart.StatList.Where(x => x.DlRbsPerSlot > 5 && x.Rsrp > -150).Select(x =>
                new { Rsrp = x.Rsrp, FE = x.DlFrequencyEfficiency }),
                JsonRequestBehavior.AllowGet);
        }
    }
}

Lte.WebApp/Views/Dingli/HandoverImport.cshtml
@model List<Lte.Evaluations.Dingli.HandoverInfo>

@{
    ViewBag.Title = "导入路测数据";
}

@section featured {
    <hgroup class="title">
        <h1>@ViewBag.Title</h1>
    </hgroup>
    
    }

<article>
    @using (Html.BeginForm("HandoverAnalyze", "Dingli",
        FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        <p class="field input">
            鼎利文件选择：
            <input type="file" name="fileUpload" />
        </p>
        <p><button type="submit">导入数据</button>
            @Html.ActionLink("导出信令", "ExportLogs", new {fileName = "results.csv"})</p>
    }
    @{ Html.RenderPartial("_HandoverInfo", Model);}
</article>

@{ Html.RenderPartial("_DtMenu");}

Lte.WebApp/Views/Dingli/List.cshtml
@model Lte.Evaluations.Dingli.TestListViewModel

@{
    ViewBag.Title = "DT数据查看";
    ViewBag.Message = "——提供日常DT数据管理、覆盖分析和部分使用小工具功能";
}

@section featured {
    <hgroup class="title">
        <h1>@ViewBag.Title</h1>
        <h2>@ViewBag.Message</h2>
    </hgroup>
}

<article>
    <div id="radiotabs">
        <ul>
            <li><a href="#dt-records">分区DT数据记录</a></li>
            <li><a href="#geography">地理化呈现</a></li>
        </ul>
        <div id="dt-records">
            @{ Html.RenderPartial("_DtRecords", Model); }
        </div>
        <div id="geography"></div>
    </div>
    <div id="dialog-modal"></div>
</article>

@{ Html.RenderPartial("_DtMenu");}

@section css{
@Styles.Render("~/Content/themes/base/css")
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Scripts/Parameters/ExtendOperations.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#radiotabs").tabs();
            $(".showdata").click(function() {
                var title = $(this).attr("id").split('-');
                var keyword;
                var district = title[1];
                switch (title[0]) {
                    case "rural":
                        keyword = "城区";
                        break;
                    case "road":
                        keyword = "国道";
                        break;
                    default:
                        keyword = "高速";
                        break;
                }
                $.ajax({
                    url: "/api/DtFileInfos/"+district+"/"+keyword,
                    type: "GET",
                    dataType: "json",
                    success: function(list) {
                        $("#dialog-modal").showDtInfoListDialog(district + keyword + '测试文件列表', list, 800, 480);
                    }
                });
            });
            $(".showraster").click(function() {
                var title = $(this).attr("id").split('-');
                var type = title[1];
                var town = title[2];
                $.ajax({
                    url: "/api/FileNames/"+town+"/"+type,
                    type: "GET",
                    dataType: "json",
                    success: function(list) {
                        $("#dialog-modal").showRasterInfoListDialog(town + type + '测试文件列表', list, type, 800, 480);
                    }
                });
            });
        });
    </script>
}

Lte.WebApp/Views/Dingli/_DtMenu.cshtml
<aside>
    <div class="box">
        <h3>路测数据分析</h3>
        <p>
            这里提供全网路测数据的管理功能，以及对鼎利或者惠捷朗路测数据的后处理和分析功能
        </p>
        <ul>
            <li>@Html.ActionLink("DT数据展示", "List", "Dingli")</li>
            <li>@Html.ActionLink("切换数据分析", "HandoverImport", "Dingli")</li>
            <li>@Html.ActionLink("速率分析", "RateImport", "Rate")</li>
            <li>@Html.ActionLink("覆盖分析", "CoverageImport", "Coverage")</li>
        </ul>
    </div>
</aside>

Lte.WebApp/Views/Dingli/_DtRecords.cshtml
@model Lte.Evaluations.Dingli.TestListViewModel

<div class="modal-body form-horizontal">
    <div class="form-group">
        <label class="col-sm-2 control-label">区域</label>
        <label class="col-sm-10 control-label">数据更新日期</label>
    </div>
    @{
        IEnumerable<string> districts = Model.TownList.Select(x => x.DistrictName).Distinct();
        foreach (string district in districts)
        {
            <div class="form-group">
                <label class="col-sm-2 control-label">@district</label>
                <div class="btn-group col-sm-10">
                    <button id="rural-@district" class="btn btn-primary showdata">
                        <span class="glyphicon glyphicon-user"></span>
                        查看城区测试数据
                    </button>
                    <button id="road-@district" class="btn btn-primary showdata">
                        <span class="glyphicon glyphicon-user"></span>
                        查看国道省道测试数据
                    </button>
                    <button id="highway-@district" class="btn btn-primary showdata">
                        <span class="glyphicon glyphicon-user"></span>
                        查看高速测试数据
                    </button>
                </div>
            </div>
            IEnumerable<string> towns = Model.TownList.Where(x => x.DistrictName == district).Select(x => x.TownName);
            foreach (string town in towns)
            {
                IEnumerable<Lte.Parameters.Service.Coverage.AreaTestDate> items =
                    Model.AreaTestDateList.Where(x => x.Area.Trim() == town);
                foreach (Lte.Parameters.Service.Coverage.AreaTestDate item in items)
                {
                    <div class="form-group">
                        <label class="col-sm-2 control-label">@item.Area</label>
                        <div class="btn-group col-sm-10">
                            @if (!string.IsNullOrEmpty(item.LatestTestDate2G))
                            {
                                <button id="list-2G-@town" class="btn btn-primary showraster">
                                    <span class="glyphicon glyphicon-user"></span>
                                    2G-@item.LatestTestDate2G.Trim()
                                </button>
                            }                           
                            @if (!string.IsNullOrEmpty(item.LatestTestDate3G))
                            {
                                <button id="list-3G-@town" class="btn btn-primary showraster">
                                    <span class="glyphicon glyphicon-user"></span>
                                    3G-@item.LatestTestDate3G.Trim()
                                </button>
                            }
                            @if (!string.IsNullOrEmpty(item.LatestTestDate4G))
                            {
                                <button id="list-4G-@town" class="btn btn-primary showraster">
                                    <span class="glyphicon glyphicon-user"></span>
                                    4G-@item.LatestTestDate4G.Trim()
                                </button>
                            }
                        </div>
                    </div>
                }
            }
        }
    }
</div>

Lte.WebApp/Views/Dingli/_HandoverInfo.cshtml
@model List<Lte.Evaluations.Dingli.HandoverInfo>

@if (Model != null && Model.Count > 0)
{ 
<table summary="User Grid" class="zebra">
<thead>
<tr style="font-weight:bold; background-color:#A8C3CB;">
	<th>请求时间</th>
    <th>完成时间</th>
    <th>测量时间</th>
    <th>切换前PCI</th>
    <th>切换后PCI</th>
    <th>切换前频点</th>
    <th>切换后频点</th>
    <th>是否成功</th>
    <th>切换前下行速率</th>
    <th>切换后下行速率</th>
</tr>
</thead>
<tbody>
@foreach (Lte.Evaluations.Dingli.HandoverInfo info in Model)
{ 
    <tr>
        <td>@info.RequestTime.ToString("HH:mm:ss.fff")</td>
        <td>@info.FinishedTime.ToString("HH:mm:ss.fff")</td>
        <td>@info.MeasureTime.ToString("HH:mm:ss.fff")</td>
        <td>@info.PciBefore</td>
        <td>@info.PciAfter</td>
        <td>@info.EarfcnBefore</td>
        <td>@info.EarfcnAfter</td>
        <td>@info.HandoverSuccess.ToString()</td>
        <td>@info.DlThroughputBefore</td>
        <td>@info.DlThroughputAfter</td>
    </tr>
}
</tbody>

</table>
}