Lte.WebApp/Controllers/Rutrace/MrsQueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using Lte.Evaluations.Service;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;

namespace Lte.WebApp.Controllers.Rutrace
{
    public class MrsQueryCoverageController : ApiController
    {
        [Route("api/MrsQueryCoverage/{topNum}")]
        public IEnumerable<MrsCellDateView> Get(int topNum)
        {
            return RutraceStatContainer.MrsStats.Take(topNum);
        }
    }

    public class MrsQueryTaController : ApiController
    {
        private readonly IMrsCellTaRepository _repository;

        public MrsQueryTaController(IMrsCellTaRepository repository)
        {
            _repository = repository;
        }

        [Route("api/MrsQueryTa/{cellId}/{sectorId}/{date}")]
        public MrsCellTa Get(int cellId, byte sectorId, DateTime date)
        {
            return _repository.GetAll().FirstOrDefault(x =>
                x.CellId == cellId && x.SectorId == sectorId && x.RecordDate == date);
        }
    }

    public class MroQueryRsrpTaController : ApiController
    {
        private readonly IMroCellRepository _repository;

        public MroQueryRsrpTaController(IMroCellRepository repository)
        {
            _repository = repository;
        }

        [Route("api/MroQueryRsrpTa/{cellId}/{sectorId}/{date}")]
        public IEnumerable<MroRsrpTa> Get(int cellId, byte sectorId, DateTime date)
        {
            return _repository.GetAll().Where(x =>
                x.CellId == cellId && x.SectorId == sectorId && x.RecordDate == date);
        }
    }
}

Lte.WebApp/Controllers/Rutrace/RutraceAnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Lte.Parameters.Entities;

namespace Lte.WebApp.Controllers.Rutrace
{
    public class RutraceAnalysisController : Controller
    {
        public JsonResult GetInterferenceRatioToVictimCellsLine(double factor)
        {
            Dictionary<int, double> values = new Dictionary<int, double>();

            for (int i = 1; i <= 100; i++)
            {
                values.Add(i, Math.Pow(i, -1 / factor));
            }

            return Json(values.Select(x => new { X = x.Key, Y = x.Value }), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAverageRtdToTaLine(double factor)
        {
            Dictionary<double, int> values = new Dictionary<double, int>{
                { 0, 0 }, { 6000 / factor, 6000 } };
            return Json(values.Select(x => new { X = x.Key, Y = x.Value }), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTaDistanceRing()
        {
            Dictionary<double, double> values = new Dictionary<double, double>();
            double radius = InterferenceStat.LowerBound;
            for (int i = 90; i >= 0; i--)
            {
                values.Add(radius * Math.Cos(i * Math.PI / 180), radius * Math.Sin(i * Math.PI / 180));
            }
            return Json(values.Select(x => new { X = x.Key, Y = x.Value }), JsonRequestBehavior.AllowGet);
        }

    }
}

Lte.WebApp/Controllers/Rutrace/RutraceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Lte.Domain.Geo.Entities;
using Lte.Domain.LinqToCsv.Context;
using Lte.Domain.LinqToCsv.Description;
using Lte.Domain.Regular;
using Lte.Evaluations.Entities;
using Lte.Evaluations.Infrastructure.Entities;
using Lte.Evaluations.Service;
using Lte.Evaluations.ViewHelpers;
using Lte.Parameters.Abstract;
using Lte.Parameters.Entities;
using Lte.Parameters.Service.Coverage;

namespace Lte.WebApp.Controllers.Rutrace
{
    public class RutraceController : Controller
    {
        private readonly IENodebRepository _eNodebRepository;
        private readonly ICellRepository _cellRepository;
        private readonly ITownRepository _townRepository;
        private readonly IMrsCellRepository _mrsRepository;
        private static IEnumerable<EvaluationOutdoorCell> outdoorCellList;

        private int PageSize { get; set; }

        public RutraceController(IENodebRepository eNodebRepository,
            ICellRepository cellRepositroy,
            ITownRepository townRepository,
            IMrsCellRepository mrsRepository)
        {
            PageSize = 10;
            _eNodebRepository = eNodebRepository;
            _cellRepository = cellRepositroy;
            _townRepository = townRepository;
            _mrsRepository = mrsRepository;
        }

        public ActionResult Import(int page = 1)
        {
            IEnumerable<ENodebBase> eNodebBases = _eNodebRepository.GetAllList().Select(x =>
                new ENodebBase
                {
                    ENodebId = x.ENodebId,
                    Name = x.Name
                });
            MrInterferenceViewModel model = new MrInterferenceViewModel
            {
                StartDate = DateTime.Today.AddDays(-7),
                EndDate = DateTime.Today
            };
            model.InitializeTownList(_townRepository, model);
            model.UpdateStats(RutraceStatContainer.MrsStats, eNodebBases, PageSize, page);
            return View(model);
        }

        [HttpPost]
        public ActionResult ImportResult(MrInterferenceViewModel model)
        {
            IEnumerable<ENodeb> eNodebs = _eNodebRepository.GetAllWithNames(_townRepository,
                model.CityName, model.DistrictName, model.TownName, model.ENodebName, model.Address);
            IEnumerable<ENodebBase> eNodebBases = eNodebs.ToList().Select(x =>
                new ENodebBase
                {
                    ENodebId = x.ENodebId,
                    Name = x.Name
                });
            if (eNodebs.Any())
            {
                MrsCellDate[] stats 
                    = _mrsRepository.QueryItems(eNodebs, model.StartDate, model.EndDate).ToArray();
                Array.Sort(stats, new MrsCellDateComparer());
                if (stats.Any())
                {
                    RutraceStatContainer.MrsStats = stats.Select(x =>
                    {
                        MrsCellDateView view = new MrsCellDateView();
                        x.CloneProperties(view);
                        ENodebBase eNodeb = eNodebBases.FirstOrDefault(e => e.ENodebId == x.CellId);
                        view.CellName = eNodeb == null ? "Unknown" : eNodeb.Name + "-" + x.SectorId;
                        return view;
                    }).ToList();
                    outdoorCellList = RutraceStatContainer.QueryOutdoorCellsFromMrs(
                        _eNodebRepository, _cellRepository);
                }
            }
            model.InitializeTownList(_townRepository, model);
            model.UpdateStats(RutraceStatContainer.MrsStats, eNodebBases, PageSize);
            return View("Import", model);
        }

        public ActionResult ExportStat(string fileName)
        {
            IEnumerable<MrsCellDateView> results = RutraceStatContainer.MrsStats;
            if (results == null) { return Redirect("Import"); }
            string absoluFilePath
                = Path.Combine(AppDomain.CurrentDomain.BaseDirectory + "uploads/", fileName);
            CsvFileDescription fileDescription = new CsvFileDescription
            {
                SeparatorChar = ',',
                FirstLineHasColumnNames = true,
                EnforceCsvColumnAttribute = true,
                TextEncoding = Encoding.GetEncoding("GB2312")
            };
            CsvContext.Write(results, absoluFilePath, fileDescription);
            return File(new FileStream(absoluFilePath, FileMode.Open),
                "application/octet-stream", Server.UrlEncode(fileName));
        }

        public ActionResult DisplayDef(StatComplexFieldRepository repository)
        {
            return View(new StatFieldViewModel(repository.FieldList[0])
            {
                FieldLength = 8,
                ColorThemeDescription = "喷漆"
            });
        }

        [HttpPost]
        public ActionResult DisplayDef(StatFieldViewModel viewModel,
            StatComplexFieldRepository repository)
        {
            for (int i = 0; i < repository.FieldList.Count; i++)
            {
                if (i == (int)viewModel.FieldName.GetStatRuIndex()
                    + StatValueChoiceQueries.Choices.Count()
                    || i == (int)viewModel.FieldName.GetStatValueIndex()
                    || repository.FieldList[i].IntervalList.Count == 0)
                {
                    repository.FieldList[i].AutoGenerateIntervals(
                        viewModel.FieldLength, viewModel.ColorThemeDescription.GetColorThemeIndex());
                }
            }
            GenerateValuesMrsService service = new GenerateValuesMrsService(RutraceStatContainer.MrsStats);
            return View(new StatFieldViewModel(repository[viewModel.FieldName],
                service.GenerateValues(viewModel.FieldName))
            {
                FieldLength = viewModel.FieldLength,
                ColorThemeDescription = viewModel.ColorThemeDescription
            });
        }

        public ActionResult ExportSectors(StatComplexFieldRepository repository)
        {
            if (RutraceStatContainer.MrsStats == null || RutraceStatContainer.MrsStats.Count == 0)
            {
                TempData["warning"] = "小区统计数据为空！请先导入并统计数据。";
                return RedirectToAction("Import");
            }

            for (int i = 0; i < StatRuChoiceQueries.Choices.Count(); i++)
            {
                StatValueField field = repository.FieldList[i + StatRuChoiceQueries.Choices.Count()];
                if (field.IntervalList.Count == 0)
                {
                    TempData["warning"] = "显示区间：" + StatRuChoiceQueries.Choices.ElementAt(0)
                        + "设置为空！请先设置区间。";
                    return RedirectToAction("DisplayDef");
                }
            }

            return View(new StatFieldsSelectionViewModel
            {
                RuFieldName = StatRuChoiceQueries.Choices.ElementAt(0),
                ValueFieldName = StatValueChoiceQueries.Choices.ElementAt(0),
                Longtitute = outdoorCellList.Where(x => x.Height > 1).Select(x => x.Longtitute).Distinct().Average(),
                Lattitute = outdoorCellList.Where(x => x.Height > 1).Select(x => x.Lattitute).Distinct().Average()
            });
        }

        public JsonResult GetStatRuField(StatComplexFieldRepository repository,
            string fieldName)
        {
            StatValueField field = repository.FieldList[(int)fieldName.GetStatRuIndex()
                + StatValueChoiceQueries.Choices.Count()];
            return Json(field.IntervalList.Select(x => new
            {
                L = x.IntervalLowLevel,
                H = x.IntervalUpLevel,
                C = x.Color.ColorStringForHtml,
                K = x.Color.ColorStringForKml
            }).ToArray(),
            JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStatValueField(StatComplexFieldRepository repository,
            string fieldName)
        {
            StatValueField field = repository.FieldList[(int)fieldName.GetStatValueIndex()];
            return Json(field.IntervalList.Select(x => new
            {
                L = x.IntervalLowLevel,
                H = x.IntervalUpLevel,
                C = x.Color.ColorStringForHtml,
                K = x.Color.ColorStringForKml
            }).ToArray(),
            JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStatField(StatComplexFieldRepository repository,
            string fieldName)
        {
            StatValueChoice valueChoice = fieldName.GetStatValueIndex();
            StatRuChoice ruChoice = fieldName.GetStatRuIndex();
            int index = (valueChoice == StatValueChoice.Undefined) ?
                (int)ruChoice + StatValueChoiceQueries.Choices.Count() :
                (int)valueChoice;
            StatValueField field = repository.FieldList[index];
            return Json(field.IntervalList.Select(x => new
            {
                L = x.IntervalLowLevel,
                H = x.IntervalUpLevel,
                C = x.Color.ColorStringForHtml,
                K = x.Color.ColorStringForKml
            }).ToArray(),
            JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStatSectors(StatComplexFieldRepository repository, string fieldName)
        {
            List<SectorTriangle> info = repository.GenerateSectors(RutraceStatContainer.MrsStats,
                outdoorCellList, fieldName);
            return Json(info, JsonRequestBehavior.AllowGet);
        }
    }
}

Lte.WebApp/Views/Rutrace/DisplayDef.cshtml
@model Lte.Evaluations.ViewHelpers.StatFieldViewModel
@using Lte.Evaluations.Infrastructure.Entities

@section featured {
            <hgroup class="title">
                <h1>小区分析显示设置</h1>
            </hgroup>
}

<section>
    <div class="row">
        <div class="col-md-3">
            <div class="one">
                <h4>指标选择</h4>
                @using (Html.BeginForm("DisplayDef", "Rutrace",
                    FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <p>
                        选择指标：
                        @Html.DropDownListFor(x => x.FieldName, StatValueChoiceQueries.Choices.Select(
                            x => new SelectListItem { Text = x, Value = x }).Concat(
                                StatRuChoiceQueries.Choices.Select(
                                    x => new SelectListItem { Text = x, Value = x })))
                    </p>
                        Html.RenderPartial("StatFieldInput", Model);
                    <p>
                        <input type="submit" class="btn btn-primary" value="生成区间" />
                        @Html.ActionLink("输出结果", "ExportSectors")
                    </p>            
                }
            </div>
        </div>
        <div class="col-md-3">
            <div class="two">
                <h4>区间设置</h4>
                @if (Model.IntervalSettingList != null && Model.IntervalSettingList.Count > 0)
                {
                    Html.RenderPartial("_IntervalSettingTable", Model.IntervalSettingList);
                    <p>
                        <button class="btn btn-primary">生成区间</button>
                    </p>
                }
                else
                {
                    <p>该指标不支持自定义区间设置</p>
                }
            </div>
        </div>
        <div class="col-md-3">
            <div class="three">
                <h4>区间颜色</h4>
                @{ Html.RenderPartial("_EvaluationIntervalTable", Model.IntervalList); }
            </div>
        </div>
    </div>
</section>

@section scripts{
<script type="text/javascript" src="../../Scripts/Parameters/StatField.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            UpdateFieldName("GetStatField");
        });
        
    </script>
}

Lte.WebApp/Views/Rutrace/ExportSectors.cshtml
@using Lte.Evaluations.Infrastructure.Entities
@model Lte.Evaluations.ViewHelpers.StatFieldsSelectionViewModel
@{
    ViewBag.Title = "仿真结果";
}

<div class="row">
    <article class="col-md-4">
        <p>
            小区指标选择：
            @Html.DropDownListFor(x => x.RuFieldName, StatRuChoiceQueries.Choices.Select(
                s => new SelectListItem { Text = s, Value = s }).ToList())
            栅格指标选择：
            @Html.DropDownListFor(x => x.ValueFieldName, StatValueChoiceQueries.Choices.Select(
                s => new SelectListItem { Text = s, Value = s }).ToList())
        </p>
        <p>
            <input type="button" class="btn btn-primary" id="refresh" value="小区指标专题"/>
            <input type="button" class="btn btn-primary" id="generation" value="覆盖图生成" />
            <input type="hidden" id="centerx" value="@Model.Longtitute" />
            <input type="hidden" id="centery" value="@Model.Lattitute" />
        </p>
    </article>
 
    <aside class="col-md-4">
        <table class="float-right">
            <tbody>
                <tr id ="colorsRu"></tr>
                <tr id="limitsRu"></tr>
                <tr id ="colorsValue"></tr>
                <tr id="limitsValue"></tr>
            </tbody>
        </table>
    </aside>
    
</div>


@section scripts{
<script type="text/javascript" src="../../Scripts/Parameters/MapContainer.js"></script>
<script type="text/javascript" src="~/Scripts/Parameters/ExtendOperations.js"></script>
<script type="text/javascript" src="~/Scripts/Parameters/EvaluationMapCanvas.js"></script>
<script type="text/javascript">
    var map = new BMap.Map("allmap");
    var point = new BMap.Point($("#centerx").val(), $("#centery").val());
    var container = new MapContainer(map);
    container.initalize(point, 15);
    var canvas = new EvaluationMapCanvas(container);

    $("#colorsRu").updateColorTag("GetStatRuField", $("#RuFieldName").val());
    $("#limitsRu").updateLimitTag("GetStatRuField", $("#RuFieldName").val());
    $("#colorsValue").updateColorTag("GetStatValueField", $("#ValueFieldName").val());
    $("#limitsValue").updateLimitTag("GetStatValueField", $("#ValueFieldName").val());
    $("#RuFieldName").change(function () {
        $("#colorsRu").updateColorTag("GetStatRuField", $(this).val());
        $("#limitsRu").updateLimitTag("GetStatRuField", $(this).val());
    });
    $("#ValueFieldName").change(function () {
        $("#colorsValue").updateColorTag("GetStatValueField", $(this).val());
        $("#limitsValue").updateLimitTag("GetStatValueField", $(this).val());
    });
    $("#refresh").click(function () {
        map.removeSectors();
        canvas.drawKpiSectors("GetStatSectors", $("#RuFieldName").val());
    });

    $("#generation").click(function () {
        canvas.removeGrids();
        canvas.updateRange();
        canvas.drawGridsWithRange("/Evaluation/ImportCellsWithRange", $("#ValueFieldName").val());
    });
</script>
}

Lte.WebApp/Views/Rutrace/Import.cshtml
@model MrInterferenceViewModel

@{
    ViewBag.Title = "LTE MR覆盖专题分析";
    ViewBag.Message = "——从数据库导入4G的MRO数据和MRS数据";
}
@using Lte.Evaluations.ViewHelpers
@using Lte.Parameters.Entities

@section featured {
    <hgroup class="title">
        <h1>@ViewBag.Title</h1>
        <h2>@ViewBag.Message</h2>
    </hgroup>
}

    <div id="radiotabs">
        <ul>
            <li><a href="#conditions">查询条件</a></li>
            <li><a href="#mrs-stat">MRS统计信息</a></li>
            <li><a href="#coverage-chart">覆盖率统计图</a></li>
            <li><a href="#tabs-4">站间距分析</a></li>
            <li><a href="#tabs-5">超远覆盖分析</a></li>
        </ul>
        <div id="conditions">
		    
            @using (Html.BeginForm("ImportResult", "Rutrace",
                FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                Html.RenderPartial("QueryConditions", Model);
                Html.RenderPartial("../Kpi/_DateSpanSelection", Model);
                <p>
                    @Html.ActionLink("显示设置", "DisplayDef")
                    @Html.ActionLink("导出结果", "ExportStat", new { fileName = "Stat.csv" })                
                </p>
            }
        </div>
	    <div id="mrs-stat">
		@{
            List<MrsCellDateView> stats = Model.MrsCells;
    
            if (stats != null)
            {
                Html.RenderPartial("_MrsStatTable", Model.MrsCells);
            <div class="pager">
                @Html.PageLinks(Model.PagingInfo, x => Url.Action("Import", new { page = x }))
            </div>
            }
        }
	    </div>
        <div id="coverage-chart">
            <p>
                选择TOP记录数：
                <select id="topnum" name="topnum">
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="50">50</option>
                </select>
                <button type="button" id="showCharts" class="btn btn-primary">
                    <span class="glyphicon glyphicon-sort-by-attributes-alt"></span>
                    图表结果展示
                </button>
            </p>
            <div id="chart_coverage" style="height:500px;width:900px; "></div>
        </div>
	    <div id="tabs-4">
		    <div id="chart_averagertd_and_taaverage" style="height:650px;width:900px; "></div>
	    </div>
        <div id="tabs-5">
            <div id="chart_taaverage_and_excessrate" style="height:650px;width:900px; "></div>
        </div>
    </div>
    <div id="dialog-modal"></div>

@section css{
@Styles.Render("~/Content/themes/base/css")
}
@section Scripts {
    <script type="text/javascript" src="~/Scripts/Dingli/RuInterferenceSet.js"></script>
    <script type="text/javascript" src="~/Scripts/Parameters/RegionRefresh.js"></script>
    <script type="text/javascript" src="~/Scripts/Dingli/ComboSetting.js"></script>
    <script type="text/javascript" src="~/Scripts/Parameters/MrsStatSet.js"></script>
    <script type="text/javascript" src="~/Scripts/Parameters/ExtendOperations.js"></script>

@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/highcharts")
<script type="text/javascript">
    $(document).ready(function () {
        $("#radiotabs").tabs();
        var region = new RegionRefresh("#CityName", "#DistrictName", "#TownName");
        $("#CityName").change(function () {
            region.getDistrictList("/api/DistrictList/" + $(this).val(), false);
        });
        $("#DistrictName").change(function () {
            region.getTownList("/api/TownList/" + $("#CityName").val() + "/" + $(this).val(), false);
        });
        $("#StartDate").datepicker({ dateFormat: 'yy-mm-dd' });
        $("#EndDate").datepicker({ dateFormat: 'yy-mm-dd' });
        $("#showCharts").click(function() {
            var setting = new ComboSetting('MR覆盖率变化趋势');
            var dataSet = new MrsStatSet(setting);
            dataSet.generateCoveragePlot("/api/MrsQueryCoverage/" + $("#topnum").val(),
                $("#chart_coverage"));
        });
        $(".show-precise").click(function() {
            var segments = $(this).attr("id").split(':');
            var eNodebId = segments[1];
            var sectorId = segments[2];
            var date = segments[3].replace('/', '-').replace('/', '-');
            var setting = new ComboSetting(segments[4] + '精确覆盖率变化趋势');
            var dataSet = new PreciseStatSet(setting);
            dataSet.generatePlot("/api/QueryPreciseStat/" + eNodebId + "/" + sectorId + "/" + date,
                $("#dialog-modal"), 900, 480);
        });

        $(".show-ta").click(function () {
            var segments = $(this).attr("id").split(':');
            var eNodebId = segments[1];
            var sectorId = segments[2];
            var date = segments[3].replace('/', '-').replace('/', '-');
            var setting = new ComboSetting(segments[4] + 'TA区间分布');
            var dataSet = new MrsStatSet(setting);
            dataSet.generateTaPlot("/api/MrsQueryTa/" + eNodebId + "/" + sectorId + "/" + date,
                $("#dialog-modal"), 900, 480);
        });

        $(".show-rsrpta").click(function () {
            var segments = $(this).attr("id").split(':');
            var eNodebId = segments[1];
            var sectorId = segments[2];
            var date = segments[3].replace('/', '-').replace('/', '-');
            var setting = new ComboSetting(segments[4] + 'RSRP-TA区间分布');
            var dataSet = new MrsStatSet(setting);
            dataSet.generateRsrpTaPlot("/api/MroQueryRsrpTa/" + eNodebId + "/" + sectorId + "/" + date,
                $("#dialog-modal"), 900, 480);
        });
    });
    
</script>
}

Lte.WebApp/Views/Rutrace/StatFieldInput.cshtml
@model Lte.Evaluations.ViewHelpers.StatFieldViewModel
@using Lte.Evaluations.Infrastructure.Entities
            
<p>
    区间数量：
    @Html.DropDownListFor(x => x.FieldLength,
        new List<SelectListItem> 
        {
            new SelectListItem { Text="4", Value="4" }, 
            new SelectListItem { Text = "6", Value = "6" },
            new SelectListItem { Text = "8", Value = "8" }
        }
        )
</p>
<p>
    颜色主题：                    
    @Html.DropDownListFor(x=>x.ColorThemeDescription,ColorThemeQueries.Choices.Select(
        x => new SelectListItem() { Text = x, Value = x }).ToList())
</p>

Lte.WebApp/Views/Rutrace/_IntervalSettingTable.cshtml
@model IList<Lte.Evaluations.Entities.StatValueIntervalSetting>

<table summary="User Grid" class="zebra">
    <thead>
        <tr style="font-weight:bold; background-color:#A8C3CB;">
	        <th>区间下限</th>
            <th>区间上限</th>
            <th>当前区间统计数量</th>
            <th>建议设定区间上限</th>
        </tr>
    </thead>
    <tbody id="interval-settings">
    @for (int i = 0; i < Model.Count; i++)
    { 
        <tr>
            <td>@Model[i].IntervalLowLevel</td>
            <td>@Model[i].IntervalUpLevel</td>
            <td>@Model[i].RecordsCount</td>
            <td>@Html.EditorFor(x=>x.ElementAt(i).SuggestUpLevel)</td>
        </tr>
    }
    </tbody>
</table>

Lte.WebApp/Views/Rutrace/_MrsStatTable.cshtml
@model IEnumerable<Lte.Parameters.Entities.MrsCellDateView>

<table summary="User Grid" class="zebra">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateString)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CellName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalMrs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CoveragePercentage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CoverageTo110)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CoverageTo115)
        </th>
        <th>
            关联分析
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateString)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CellName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalMrs)
        </td>
        <td>
            @String.Format("{0:0.00}", item.CoveragePercentage)
        </td>
        <td>
            @String.Format("{0:0.00}", item.CoverageTo110)
        </td>
        <td>
            @String.Format("{0:0.00}", item.CoverageTo115)
        </td>
        <td>
            <div class="btn-group">
                <button id="precise:@item.CellId:@item.SectorId:@item.DateString:@item.CellName"
                    class="btn btn-primary show-precise">精确覆盖率分析</button>
                <button id="ta:@item.CellId:@item.SectorId:@item.DateString:@item.CellName"
                    class="btn btn-primary show-ta">TA区间分布</button>
                <button id="rsrpta:@item.CellId:@item.SectorId:@item.DateString:@item.CellName"
                    class="btn btn-primary show-rsrpta">RSRP-TA联合分析</button>
            </div>
        </td>
    </tr>
}

</table>

Lte.WebApp/Views/Rutrace/_RuInterferenceStatTable.cshtml
@model List<Lte.Evaluations.Rutrace.Record.RuInterferenceStat>

<table summary="User Grid" class="zebra">
        <thead>
            <tr style="font-weight:bold; background-color:#A8C3CB;">
                <th>LTE小区名称</th>
                <th>CDMA小区名称</th>
                <th>ENodeb ID</th>
                <th>小区编号</th>
                <th>扇区编号</th>
                <th>干扰小区数</th>
                <th>干扰比例</th>
                <th>最小RTD</th>
                <th>平均RTD</th>  
                <th>最大TA</th>
                <th>平均TA</th>
                <th>超远覆盖比例</th>
            </tr>
        </thead>
        <tbody>
        @foreach (Lte.Evaluations.Rutrace.Record.RuInterferenceStat stat in Model)
        { 
            <tr>
                <td>@stat.LteCellName</td>
                <td>@stat.CdmaCellName</td>
                <td>@stat.ENodebId</td>
                <td>@stat.CellId</td>
                <td>@stat.SectorId</td>
                <td>@stat.VictimCells</td>
                <td>@String.Format("{0:0.00}", stat.InterferenceRatio*100)%</td>
                <td>@String.Format("{0:0.00}", stat.MinRtd)</td>
                <td>@String.Format("{0:0.00}", stat.AverageRtd)</td>
                <td>@String.Format("{0:0.00}", stat.TaMax)</td>
                <td>@String.Format("{0:0.00}", stat.TaAverage)</td>
                <td>@String.Format("{0:0.00}", stat.TaExcessRate*100)%</td>
            </tr>
        }
        </tbody>
    </table>